Chamois project

## Libraries and datasets
```{r lib_data}
rm(list = ls())

# load the data
ch_biom <- read.csv("data/data.csv")
clim <- read.csv("data/swiss_weather.csv")

# load the packages
library(dplyr)
library(climwin)
library(tidyr)
library(ggplot2)
library(effects)
library(lme4)
library(lmerTest)

colnames(ch_biom) <- snakecase::to_snake_case(colnames(ch_biom))

head(ch_biom)
summary(ch_biom)

# explore
boxplot(ch_biom$day ~ ch_biom$year)

# create a nice formats for the date
# create a new column with YMD
ch_biom$date_ymd <- paste(ch_biom$year, ch_biom$month, ch_biom$day)
# fix the format of the date
ch_biom$date_ymd <- as.Date(ch_biom$date_ymd, "%Y %m %d")
clim$date_ymd <- as.Date(clim$date, "%Y/%m/%d")

ch_biom <- ch_biom %>%
  select(-c("x_1"))

# explore the data
names(ch_biom)
summary(ch_biom)

# get only data with 1.5 years old individuals
ch_biom <- ch_biom %>%
  drop_na() %>%
  filter(age == "1.5")

ch_biom$year_f <- as.factor(ch_biom$year)
ch_biom$district_capture <- as.factor(ch_biom$district_capture)
summary(ch_biom$district_capture)
summary(ch_biom)
```


```{r basemod}
ch_basemod <- lm(weight ~
  sex + altitude,
data = ch_biom
)

ch_basemod_lmer <- lme4::lmer(weight ~
  sex + altitude +
  (1 | year_f) + (1 | district_capture),
control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e+06)),
REML = TRUE,
data = ch_biom
)

summary(ch_basemod_lmer)
par(mfrow = c(1, 2))
visreg::visreg(ch_basemod)
par(mfrow = c(1, 1))

ranova(ch_basemod_lmer)
drop1(ch_basemod_lmer)
```

## Juveniles

```{r juv climmod, eval = F}
# create model with ABSOLUTE time window
# with snow & temperature for 1 year before

absolute_juvenile_lmer <- slidingwin(
  baseline = ch_basemod_lmer,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(150, 0),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day"
)
save(absolute_juvenile_lmer, file = "output/absolute_juvenile_lmer.rda")


absolute_juvenile <- slidingwin(
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(150, 0),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day"
)
save(absolute_juvenile, file = "output/absolute_juvenile.rda")
```

```{r}

load("output/absolute_juvenile.rda")

absolute_juvenile$combos
# provides a summary of all tested climate window hypotheses,
# with the key statistics from the best model included

# View output for func = "quad" and mean temperature
head(absolute_juvenile[[2]]$Dataset)
# we can look at the full dataset of all fitted climate windows.
# in this list the models are sorted by deltaAICc,
# such that the best supported model is on top.

# The best time window is between day 108 and 66 - AIC= -297.7070
summary(absolute_juvenile[[2]]$BestModel)
# the results from the best supported model for each hypothesis

# head(absolute_juvenile[[2]]$BestModel)
# Finally, the object BestModel stores the values of the climate signal
# that was best supported by the data and the row numbers correspond
# to the original row numbers of the Biol dataset.


# plot results from best model
plotall(
  dataset = absolute_juvenile[[2]]$Dataset,
  bestmodel = absolute_juvenile[[2]]$BestModel,
  bestmodeldata = absolute_juvenile[[2]]$BestModelData
)

# extracting best window and attaching it to the original dataset
ch_biom$t_abs_juvenile <- absolute_juvenile[[2]]$BestModelData$climate


# Running the best model in R
m_j <- lm(weight ~
  sex + altitude + t_abs_juvenile + I(t_abs_juvenile^2),
data = ch_biom
)


summary(m_j)

plot(allEffects(m_j))
```


```{r eval = F}
# Performing randomization to identify likelihood of signals occurring by chance

randomized_juvenile <- climwin::randwin(
  repeats = 1000,
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(150, 0),
  stat = c("mean"),
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day",
  window = "sliding"
)

save(randomized_juvenile, file = "output/rand_juv.rda")
```
```{r}
load("output/rand_juv.rda")
pvalue(
  datasetrand = randomized_juvenile[[1]],
  dataset = absolute_juvenile[[1]]$Dataset, metric = "C", sample.size = 27
) # the p-value is 0.0008406281
```


## Kids

```{r kid climmod, eval = F}
# create model with ABSOLUTE time window temperature for 1y before till 1 June
absolute_kid <- slidingwin(
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(480, 365),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day"
)

save(absolute_kid, file = "output/absolute_kid.rda")
```
```{r}
load("output/absolute_kid.rda")
absolute_kid$combos
# provides a summary of all tested climate window hypotheses,
# with the key statistics from the best model included


# View output for func = "quad" and mean temperature

head(absolute_kid[[2]]$Dataset)
# we can look at the full dataset of all fitted climate windows.
# in this list the models are sorted by deltaAICc,
# such that the best supported model is on top.

# The best time window is between day 504 and 450 - AIC= -320.1128
summary(absolute_kid[[2]]$BestModel)
# the results from the best supported model for each hypothesis

head(absolute_kid[[2]]$BestModel)
# Finally, the object BestModel stores the values of the climate signal
# that was best supported by the data and the row numbers correspond
# to the original row numbers of the Biol dataset.

# plot results from best model
plotall(
  dataset = absolute_kid[[2]]$Dataset,
  bestmodel = absolute_kid[[2]]$BestModel,
  bestmodeldata = absolute_kid[[2]]$BestModelData
)

# extracting best window
ch_biom$t_abs_kid <- absolute_kid[[2]]$BestModelData$climate


# Plotting some of your results
## http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/


ggplot(ch_biom, aes(x = year, y = t_abs_kid)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = lm)
# Add linear regression line (by default includes 95% confidence region)

ggplot(ch_biom, aes(x = t_abs_kid, y = weight)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = "loess")
# Add linear regression line (by default includes 95% confidence region)

# Running the best model in R

m_k <- lm(weight ~
  sex + altitude + t_abs_kid + I(t_abs_kid^2),
data = ch_biom
)


summary(m_k)

plot(allEffects(m_k))

ch_biom$altitude_sc <- scale(ch_biom$altitude)
ch_biom$t_abs_juvenile_sc <- scale(ch_biom$t_abs_juvenile)
ch_biom$t_abs_kid_sc <- scale(ch_biom$t_abs_kid)





# Comparing absoulte_juvenile and absolute_kid

# Is the effect of temperature the same whatesoever the eleavation
# testing for interaction (*) between altitude and temp
m2_1 <- lm(weight ~
  sex + scale(altitude) * (scale(t_abs_juvenile) +
    I(scale(t_abs_juvenile)^2) + scale(t_abs_kid) +
    I(scale(t_abs_kid)^2)),
data = ch_biom
)
summary(m2_1)
anova(m2_1)
visreg::visreg(m2_1)

# Do we have interactive effects of temp as kid and juvenile
m2_2 <- lm(weight ~
  sex + scale(altitude) +
  scale(t_abs_juvenile) * scale(t_abs_kid) +
  I(scale(t_abs_juvenile)^2) + I(scale(t_abs_kid)^2),
data = ch_biom
)
summary(m2_2)
visreg::visreg(m2_2)

# scaling and centering
# (subtracting the mean and reducing (dividing by standard deviation))
non_scd <- ch_biom$t_abs_juvenile
mean(non_scd)
sd(non_scd)

scaled <- scale(ch_biom$t_abs_juvenile)
mean(scaled)
sd(scaled)

par(mfrow = c(1, 2))
hist(non_scd)
hist(scaled)
```
```{r kid random, eval = F}
# Performing randamization to identify
# likelyhood of of dignals occuring by chance

randomized_kid <- randwin(
  repeats = 1000,
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(480, 365),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"), cmissing = FALSE, cinterval = "day",
  window = "sliding"
)

save(randomized_kid, file = "output/rand_kid.rda")
```
```{r}
load("output/rand_kid.rda")

pvalue(
  datasetrand = randomized_kid[[1]],
  dataset = absolute_kid[[1]]$Dataset, metric = "C", sample.size = 27
) # 0.0006408258
```

## Gestation

```{r gest climmod, eval = F}
# create model with ABSOLUTE time window with temperature for gestation period
# for the period 1 Dec(-2) - 31May(-1)
absolute_gestation <- slidingwin(
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(661, 481),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day"
)

save(absolute_gestation, file = "output/absolute_gestation.rda")
```
```{r}
load("output/absolute_gestation.rda")
absolute_gestation$combos
# provides a summary of all tested climate window hypotheses,
# with the key statistics from the best model included


# View output for func = "quad" and mean temperature

head(absolute_gestation[[2]]$Dataset)
# we can look at the full dataset of all fitted climate windows.
# in this list the models are sorted by deltaAICc,
# such that the best supported model is on top.

# The best time window is between day 756 and 756- AIC= --186.7308
summary(absolute_gestation[[2]]$BestModel)
# the results from the best supported model for each hypothesis

head(absolute_gestation[[2]]$BestModel)
# Finally, the object BestModel stores the values of the climate signal
# that was best supported by the data and the row numbers correspond
# to the original row numbers of the Biol dataset.

# The best supported climate variable can be attached
# to the original dataset for further analyses
ch_biom$signal <- absolute_gestation[[2]]$BestModel$clim

# plot results from best model
plotall(
  dataset = absolute_gestation[[2]]$Dataset,
  bestmodel = absolute_gestation[[2]]$BestModel,
  bestmodeldata = absolute_gestation[[2]]$BestModelData
)
# Warning message:
# In plotwin(dataset = ch_biomset, cw = cwa) :
# Top window has a weight greater than 0.95. Plotting single best window only.

# extracting best window
ch_biom$t_abs_gestation <- absolute_gestation[[2]]$BestModelData$climate


# Running the best model in R

m_g <- lm(weight ~
  sex + altitude + t_abs_gestation + I(t_abs_gestation^2),
data = ch_biom
)


summary(m_g)

visreg::visreg(m_g)

# model for all three stages

# Comparing absoulte_juvenile, absolute_kid and absolute_gestation

ch_biom$altitude_sc <- scale(ch_biom$altitude)
ch_biom$t_abs_juvenile_sc <- scale(ch_biom$t_abs_juvenile)
ch_biom$t_abs_kid_sc <- scale(ch_biom$t_abs_kid)
ch_biom$t_abs_gestation_sc <- scale(ch_biom$t_abs_gestation)


# Is the effect of temperature the same whatesoever the eleavation
# testing for interaction (*) between altitude and temp
m3 <- lm(weight ~
  sex + scale(altitude) *
    (scale(t_abs_juvenile) + I(scale(t_abs_juvenile)^2) +
      scale(t_abs_kid) + I(scale(t_abs_kid)^2) +
      scale(t_abs_gestation) + I(scale(t_abs_gestation)^2)),
data = ch_biom
)

summary(m3)


visreg::visreg(m3)

m3_sc <- lm(weight ~
  sex + (ch_biom$altitude_sc) * (ch_biom$t_abs_juvenile_sc) +
  I((ch_biom$t_abs_juvenile_sc)^2) + (ch_biom$t_abs_kid_sc) +
  I((ch_biom$t_abs_kid_sc)^2) + (ch_biom$t_abs_gestation_sc) +
  I((ch_biom$t_abs_gestation_sc)^2),
data = ch_biom
)


# Do we have interactive effects of temp as kid, juvenile and during gestation
m3_1 <- m3_1 <- lm(weight ~
  sex + scale(altitude) +
  scale(t_abs_juvenile) * scale(t_abs_kid) * scale(t_abs_gestation) +
  I(scale(t_abs_juvenile)^2) +
  I(scale(t_abs_kid)^2 +
    I(scale(t_abs_gestation)^2)),
data = ch_biom
)


summary(m3_1)

visreg::visreg(m3_1)
m_result1 <- lm(ch_biom$weight ~ sex + altitude_sc +
  t_abs_juvenile_sc * t_abs_kid_sc * t_abs_gestation_sc +
  I(t_abs_juvenile_sc)^2 + I(t_abs_kid_sc)^2 +
  I(t_abs_gestation_sc)^2,
data = ch_biom
)
```

```{r gest random, eval = F}
# Performing randomization to identify likelihood of signals occuring by chance

randomized_gestation <- randwin( # nolint
  repeats = 1000, # nolint
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(661, 481),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day",
  window = "sliding"
)

save(randomized_gestation, file = "output/rand_gest.rda")
```
```{r}
load(file = "output/rand_gest.rda")

pvalue(
  datasetrand = randomized_gestation[[1]],
  dataset = absolute_gestation[[2]]$Dataset, metric = "C", sample.size = 27
) # 0.0008195284

# combining all three models together - scaled
m_results <- lm(weight ~
  sex + altitude_sc + t_abs_juvenile_sc + t_abs_kid_sc +
  t_abs_gestation_sc + +I(t_abs_juvenile_sc^2) +
  I(t_abs_kid_sc^2) + I(t_abs_gestation_sc^2),
data = ch_biom
)

summary(m_results)

plot(allEffects(m_results))



# combining all three models together - non scaled
m_results2 <- lm(weight ~
  sex + altitude + t_abs_juvenile + t_abs_kid +
  t_abs_gestation + I(t_abs_juvenile^2) +
  I(t_abs_kid^2) + I(t_abs_gestation^2),
data = ch_biom
)


summary(m_results2)

plot(allEffects(m_results2))



# combining all three models together - scaled
m_results <- lm(weight ~
  sex + altitude_sc + t_abs_juvenile_sc + t_abs_kid_sc +
  I(t_abs_juvenile_sc^2) + I(t_abs_kid_sc^2),
data = ch_biom
)


summary(m_results)

plot(allEffects(m_results))



# combining all three models together - non scaled
m_results2 <- lm(weight ~
  sex + altitude + t_abs_juvenile + t_abs_kid +
  I(t_abs_juvenile^2) + I(t_abs_kid^2),
data = ch_biom
)


summary(m_results2)

plot(allEffects(m_results2))
```



```{r}

# Plotting some of your results
## http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/


ggplot(ch_biom, aes(x = year, y = t_abs_juvenile)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = "lm") +
  # Add linear regression line (by default includes 95% confidence region)
  scale_x_continuous(breaks = c(1992, 1997, 2002, 2007, 2013, 2018)) +
  xlab("Year") +
  ylab("Mean temperature of the best climatic window for Juvenille stage (°C)") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 20),
    axis.line = element_line(
      size = 1, linetype = "solid",
      colour = "black"
    )
  )


ggplot(ch_biom, aes(x = year, y = t_abs_kid)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = "lm") +
  # Add linear regression line (by default includes 95% confidence region)
  scale_x_continuous(breaks = c(1992, 1997, 2002, 2007, 2013, 2018)) +
  xlab("Year") +
  ylab("Mean temperature of the best climatic window for Juvenille stage (°C)") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 20),
    axis.line = element_line(
      size = 1, linetype = "solid",
      colour = "black"
    )
  )


# graph with fitted line
ggplot(ch_biom, aes(x = year, y = weight)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_continuous(breaks = c(1992, 1997, 2002, 2007, 2013, 2018)) +
  xlab("Year") +
  ylab("Weight of Alpine chamois (kg)") +
  theme_bw()

ggplot(ch_biom, aes(x = year, y = t_abs_kid)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = lm)
# Add linear regression line (by default includes 95% confidence region)



ggplot(ch_biom, aes(x = t_abs_juvenile, y = weight)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = "loess")
# Add linear regression line (by default includes 95% confidence region)




ggplot(ch_biom, aes(x = year, y = t_abs_gestation)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = lm)
# Add linear regression line (by default includes 95% confidence region)

ggplot(ch_biom, aes(x = t_abs_gestation, y = weight)) +
  geom_point(shape = 1) +
  # Use hollow circles
  geom_smooth(method = "loess")
# Add linear regression line (by default includes 95% confidence region)
```


## ALL


```{r all climmod, eval = F}
# create model with ABSOLUTE time window with temperature for ALWAYS period
# for the period 1 Dec(-2) - 31May(-1)
absolute_all <- slidingwin(
  baseline = ch_basemod,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(661, 0),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day"
)

save(absolute_all, file = "output/absolute_all.rda")


ch_biom$t_503_449 <- absolute_all[[2]]$BestModelData$climate

ch_basemod2 <- lm(weight ~
  sex + altitude + t_503_449 + I(t_503_449^2),
data = ch_biom
)
summary(ch_basemod2)

absolute_all2 <- slidingwin(
  baseline = ch_basemod2,
  xvar = list(Temp = clim$Temp),
  type = "absolute",
  refday = c(24, 9),
  range = c(661, 0),
  stat = "mean",
  cdate = clim$date_ymd,
  bdate = ch_biom$date_ymd,
  func = c("lin", "quad"),
  cmissing = FALSE,
  cinterval = "day"
)

save(absolute_all2, file = "output/absolute_all2.rda")
```


```{r}
load(file = "output/absolute_all.rda")
absolute_all$combos

absolute_all2$combos
# provides a summary of all tested climate window hypotheses,
# with the key statistics from the best model included


# View output for func = "quad" and mean temperature

head(absolute_all[[2]]$Dataset)

head(subset(absolute_all[[2]]$Dataset, WindowClose < 300))
# we can look at the full dataset of all fitted climate windows.
# in this list the models are sorted by deltaAICc,
# such that the best supported model is on top.

# The best time window is between day 756 and 756- AIC= --186.7308
summary(absolute_all[[2]]$BestModel)
# the results from the best supported model for each hypothesis

head(absolute_all[[2]]$BestModel)
# Finally, the object BestModel stores the values of the climate signal
# that was best supported by the data and the row numbers correspond
# to the original row numbers of the Biol dataset.

# The best supported climate variable can be attached
# to the original dataset for further analyses
ch_biom$signal <- absolute_all[[2]]$BestModel$clim

# plot results from best model
plotall(
  dataset = absolute_all[[2]]$Dataset,
  bestmodel = absolute_all[[2]]$BestModel,
  bestmodeldata = absolute_all[[2]]$BestModelData
)


plotwin(dataset = absolute_all[[2]]$Dataset)

plotdelta(dataset = absolute_all[[2]]$Dataset)

# Warning message:
# In plotwin(dataset = ch_biomset, cw = cwa) :
# Top window has a weight greater than 0.95. Plotting single best window only.

# extracting best window
```

## Long term trends


```{r}


ggplot(ch_biom, aes(x = year, y = weight)) + # graph with fitted line
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(1992, 2018, 5)) +
  xlab("Year") +
  ylab("Weight of Alpine chamois (kg)") +
  theme_bw()



linear_model <- lm(weight ~ year, data = ch_biom) # making the linear model

mod_01 <- lm(weight ~ year + I(year^2), data = ch_biom)
summary(mod_01)
visreg::visreg(mod_01)
anova(linear_model)
summary(linear_model)

ggplot(ch_biom, aes(x = year, y = weight, color = sex)) +
  # difference in sex graph
  geom_point(size = 1) +
  xlab("Year") +
  ylab("Weight") +
  geom_smooth(method = "loess", se = TRUE) +
  theme_bw()

ggplot(ch_biom, aes(x = altitude, y = weight, color = sex)) +
  geom_point() +
  geom_smooth(method = "loess", se = TRUE)



model_yr <- lm(weight ~ year * sex + altitude, data = ch_biom)
summary(model_yr)
par(mfrow = c(1, 2))
visreg::visreg(model_yr, "year", by = "sex")
par(mfrow = c(1, 1))
```